name: GitHub Trending Stats

on:
  schedule:
    - cron: '0 0 * * 0'  # 每周日凌晨运行
  workflow_dispatch:      # 允许手动触发

jobs:
  collect-stats:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0    # 获取完整的git历史
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'      # 启用pip缓存
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
        
    - name: Run stats collection
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 添加错误处理
        python github_trending_stats.py || {
          echo "Error running stats collection"
          exit 1
        }
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # 检查是否有更改
        if [[ -n "$(git status --porcelain)" ]]; then
          git add stats/ README.md
          git commit -m "Update trending stats $(date '+%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi
      
    - name: Upload stats as artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: trending-stats
        path: |
          stats/
          README.md
        retention-days: 30
